// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://khwpljqvkuzftvxdervq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtod3BsanF2a3V6ZnR2eGRlcnZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0NzcyMzQsImV4cCI6MjA3MzA1MzIzNH0.sCK4oGo2r0hyigPO5cAwiFWtgaPGc_Cj_8b5DC2LiVU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const serverStorage = {
  getItem: (_key: string) => null,
  setItem: (_key: string, _value: string) => {},
  removeItem: (_key: string) => {},
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? window.localStorage : serverStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});